import { SettingSchemaDesc } from '@logseq/libs/dist/LSPlugin.user'

export const settings: SettingSchemaDesc[] = [
    {
        key: "username",
        title: "Username",
        description: "Username used in Basic Auth to get RSS feed xml file (if there was a better way from Jira, I'd do it)",
        type: "string",
        default: null,
    },
    {
        key: "password",
        title: "API Key",
        description: "API Key used in Basic Auth to get RSS feed xml file (if there was a better way from Jira, I'd do it)",
        type: "string",
        default: null,
    },
    {
        key: "host",
        title: "Jira Instance",
        description: "Jira Instance Host URL. example: https://constoso.atlassian.net/",
        type: "string",
        default: null,
    },
    {
        key: "account_id",
        title: "Account ID",
        description: "parameter key/value string of 'account-id' generated by rss link button from Activity Streams widget. Include the whole parameter &streams=account-id*",
        type: "string",
        default: null,
    },
    {
        key: "key",
        title: "JIRA Issue Key",
        description: "parameter key/value string of 'key' generated by rss link button from Activity Streams widget. Include the whole parameter &streams=key*",
        type: "string",
        default: null,
    },
    {
        key: "activity",
        title: "Activity",
        description: "parameter key/value string of 'activity' generated by rss link button from Activity Streams widget. Include the whole parameter &issues=activity*",
        type: "string",
        default: null,
    },
    {
        key: "issue_type",
        title: "Issue Type",
        description: "parameter key/value string of 'issue_type' generated by rss link button from Activity Streams widget. Include the whole parameter &issues=issue_type*",
        type: "string",
        default: null,
    },
    {
        key: "project_category",
        title: "Project Category",
        description: "parameter key/value string of 'project_category' generated by rss link button from Activity Streams widget. Include the whole parameter &issues=project_category*",
        type: "string",
        default: null,
    },
]